apiVersion: v1
kind: Service
metadata:
  name: was-svc
  annotations:
    cloud.google.com/backend-config: '{"default": "my-backend-config"}'
spec:
  selector:
    app: was
  ports: 
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: sojh5741aws/mini:backend-https-v10
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
# MARIADB_HOST
        - name: MARIADB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MARIADB_HOST
# MARIADB_PORT
        - name: MARIADB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MARIADB_PORT
# MARIADB_DATABASE
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_DATABASE
# MARIADB_USER
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_USER
# MARIADB_PASSWORD
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MARIADB_PASSWORD
# FRONTEND_URL
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FRONTEND_URL