apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MARIADB_HOST: "db-svc"
  MARIADB_PORT: "3306"
  FRONTEND_URL: "https://www.so-cute.shop"
  REACT_APP_API_BASE_URL: "https://www.so-cute.shop" #"http://was-svc.default.svc.cluster.local:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS `user` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `username` varchar(50) NOT NULL,
      `email` varchar(100) NOT NULL,
      `password` varchar(255) NOT NULL,
      `created_at` timestamp NULL DEFAULT current_timestamp(),
      `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
      PRIMARY KEY (`id`),
      UNIQUE KEY `username` (`username`),
      UNIQUE KEY `email` (`email`)
    );

    CREATE TABLE IF NOT EXISTS `board` (
      `b_idx` int(11) NOT NULL AUTO_INCREMENT,
      `row_span` int(11) DEFAULT NULL,
      `column_span` int(11) DEFAULT NULL,
      `title` varchar(300) DEFAULT NULL,
      `content` text DEFAULT NULL,
      `likes` int(11) DEFAULT 0,
      `dislikes` int(11) DEFAULT 0,
      `username` varchar(50) DEFAULT NULL,
      PRIMARY KEY (`b_idx`),
      KEY `fk_board_user` (`username`),
      CONSTRAINT `fk_board_user` FOREIGN KEY (`username`) REFERENCES `user` (`username`) ON DELETE SET NULL ON UPDATE CASCADE
    );
