apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: MTIzNA== # base64 encoded '1234'
  MARIADB_DATABASE: bWluaQ== # base64 encoded 'mini'
  MARIADB_USER: YWFtYXpvb25TMw== # base64 encoded 'amazoonS3'
  MARIADB_PASSWORD: MTIzNA== # base64 encoded '1234'